version: '3'
services:
  mygoflaskproject:
    image: tscci/mygoflaskproject:amd64
    container_name: mygo
    restart: unless-stopped
    volumes:
      - ./vedio:/vedio
    ports:
      - 5000:15000

~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
~                                                                                                      
-- INSERT --                                                                         1,1           All
